### PR TITLE
Network error and progress

### PR DESCRIPTION
**Pull request by khushbooivksp**
. component error
. on hitting search, Integrate network error and failed errors with retry button
. show progress of loading

https://www.pivotaltracker.com/n/projects/1878933/stories/137506495

<b>Chain PR</b>

### CODE REVIEW

**Comment by anshulagarwal06** [comment]
Some of code already in #12 PR.
Change base branch to urls branch

**Comment by khushbooivksp** [comment]
@anshulagarwal06  done

**Comment by anshulagarwal06** [comment]
Where are we making api call ?

**Review by anshulagarwal06 — APPROVED** [review]
lgtm

**Pull request merged**
